// Generated by scripts/x4_r10_ble_probe_deploy.sh.
// Do not edit manually during a deploy run.

pub const R10_BLE_X4_COMPILED_MODE: &str = "reader_remote";
pub const R10_BLE_X4_COMPILED_ALLOW_READER_REMOTE: &str = "1";
pub const R10_BLE_X4_COMPILED_SETTINGS: &str = "1";

pub const fn r10_ble_x4_compiled_mode_opt() -> Option<&'static str> {
    Some(R10_BLE_X4_COMPILED_MODE)
}

pub const fn r10_ble_x4_compiled_allow_reader_remote_opt() -> Option<&'static str> {
    Some(R10_BLE_X4_COMPILED_ALLOW_READER_REMOTE)
}

pub const fn r10_ble_x4_compiled_settings_opt() -> Option<&'static str> {
    Some(R10_BLE_X4_COMPILED_SETTINGS)
}
